### ISSUE TITLE
Stub out bullet class

### ISSUE THREAD

**Issue by abell95** [abell95/galaga_invaders#10]
Create base logic for bullet class - which represents the bullets the player ship fires

**Comment by abell95** [comment]
Commit : https://github.com/abell95/galaga_invaders/commit/d76577da77205d7f2bb7148d63a65bdd9f72a358

Requires additional work, left broken logic in player.rb that requires cleanup

**Comment by bmchristensen** [comment]
We are not using the term "bullet" for anything in the domain of this project. The func spec uses "missile." This should be changed to "missile."
